### ISSUE TITLE
connect two files / Pokemon to fight

### ISSUE THREAD

**Issue by ICOURR** [fedorablewill/ptu-tools#83] opened 2024-02-09 18:16 UTC
I know it would probably be a lot of work for you guys, but the software would go into another dimension if you could load two (or more?) files at the same time to click on file A uses move X on file B. That would be such a huge change, it would change the whole way you use the software.
It would really change the dynamic of the battles because switching from one tab to another and reporting all the stats manually is really laborious. 
Thanks so much for PTU though!

**Comment by fedorablewill** [comment] 2024-02-10 04:51
Thank you for your suggestion!!! I'm so honored you like my webapp! Though you need not thank me for PTU itself seeing as I'm not affiliated with them 😅

Closing ticket. Duplicate of the "Boxes" feature that is planned for the future (see https://github.com/fedorablewill/ptu-tools/milestone/2 ). And automating the taking of damage by targeting a pokemon on another player's computer is not something I wish to do for reasons I've outlined in my response in Discord.

If you have any more suggestions, let me know!

**Closed by fedorablewill** 2024-02-10 04:51 UTC
